version: '3.3'
services:
  web:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    #links:
    #  - php
    networks:
      - application

  php:
    image: php:7-fpm
    container_name: codeigniter_app
    volumes:
      - ./code:/code
    networks:
      - application
  
  #db:
  #  image: mysql:5.7
  #  container_name: db
  #  restart: unless-stopped
  #  tty: true
  #  ports:
  #    - "3306:3306"
  #  environment:
  #    MYSQL_DATABASE: homestead
  #    MYSQL_ROOT_PASSWORD: secret
  #    MYSQL_USER: homestead
  #    MYSQL_PASSWORD: secret
  #    SERVICE_TAGS: dev
  #    SERVICE_NAME: mysql
  #  volumes:
  #    - dbdata:/var/lib/mysql
  #    - ./my.cnf:/etc/mysql/my.cnf
  #  networks:
  #    - application

networks:
  application:

volumes:
  dbdata:
    driver: local